---
title: "無題の論文"
date: "`r Sys.Date()`"
author: "RMDJA太郎"
abstract: "`rmdja` パッケージは, `rmarkdown` および `bookdown` パッケージで自然なレイアウトの日本語文書を作成する際に必要な煩雑な設定を自動で行い, ユーザーの負担を軽減するために作成されたパッケージである."
output:
  rmdja::pdf_document2_ja:
    latex_engine: lualatex
documentclass: bxjsarticle
classoption:
  - a4paper
  - 'number-of-lines=30'  # 1頁30行, ただし見出しは別
  - 'textwidth=40zw'      # 1行全角40字, ただしプロポーショナルフォントなので絶対ではない
header-includes:
  - \setlength{\parindent}{4pt}
  - \setlength{\parskip}{0pt}
---

\newpage

```{r init, include=F}
require(knitr)
require(tidyverse)
# グラフの標準フォント設定
# うまく行かない場合は手動で設定してください
rmdja::set_graphics_font(rmdja::get_default_font_family("lualatex")["serif"])
```

# イントロダクション {#introduction}


　現代の日本の政治および地方自治における一つの問題は、地方議会議員・自治体首長のなり手不足、すなわち選挙における立候補者の減少及びそれに伴う無投票当選の増加がある。例えば、2019年4月に行われた第19回統一地方選挙においては、立候補者が定員に満たないために無投票当選となった当選者の割合は41 の道府県議会選挙で26.9％、121 の町村長選挙で45.5%、375の町村議会議員選挙で23.3%にそれぞれ達し、道府県議会選挙及び町村議会議員選挙では記録が残る1951 年以降の統一地方選挙において過去最高の水準となっている。\par
　こうした選挙における立候補人数の減少や無投票当選の増加は、地方自治体の重要な役職の選定に関して住民の選択の余地を狭めてしまうために、政治能力が高くない人をそうした役職に就任させてしまい、地方自治の質の低下という問題を招く可能性がある。\par
　議員・首長の立候補者不足及びそれに起因する地方自治の質の低下を防ぐ方策としては、これらの役職の待遇の向上が挙げられる。その具体策の一つが、議員・首長報酬の増額である。実際に全国町村議会議長会も町村議会議員について、その報酬の増額がなり手不足の問題の解決に寄与する可能性があることを指摘しており、彼らが設置した議員報酬の検討委員会は、2019年3月時点において全国の町村議会のうち約４割で議員報酬見直しの検討が行われていることを報告している（町村議会議員の議員報酬等のあり方検討委員会,2019）。\par
　一方で、こうした議員・首長報酬の増額は、当然ながら一定の財政支出を伴うものであり、そのコストに見合うだけの効果があるかどうかには一定の議論がある(総務省自治行政局行政課,2017など)。そこでこのような重要な議論の進展に寄与するために、今回の研究では、特に議会・議員に着目し、日本の市町村レベルのパネルデータを用いて議員報酬額が選挙における立候補人数及び議会の活動状況に与える影響を推定し、議員報酬の増額の効果を定量的に明らかにする。\par
　もちろん、こうした政治家の報酬が立候補や政治のパフォーマンスに与える影響は政治学や経済学の分野において、過去に分析の対象とされている。実証研究としては、報酬が外生的に決定される自然実験的な状況を利用してこうした影響を推定したGagliarducci and Nannicini(2013), Ferraz and Finan(2009)や、構造モデルを用いてこの影響を分析したKeane and Merlo(2010)などが良く知られている。このうち、Gagliarducci and Nannicini(2013)はイタリアの市町村のデータを用い、報酬の上昇により教育年数の長い人や専門的な職業に就いていた人が首長に立候補する傾向、また当選者が財政面でより健全な行政運営を行う傾向が強まることを示している。また、Ferraz and Finan(2009)はブラジルの地方議会に関して報酬額が高くなるほど議員の条例提案数や議員提案条例の可決数が増加すること、Keane and Merlo(2010)はアメリカの連邦議会上下院に関して議員報酬の削減は特に能力の高い議員の議会からの退出を招くことを、それぞれ明らかにしている。\par
　しかしながら、こうした分析のほとんどは欧州や米大陸の議会がその対象であり、これらの分析の報酬額がパフォーマンスに正の影響を与えるという結果が必ずしも日本の地方議会においても当てはまるとは限らない。根拠としてはMessner and Polborn(2004)やMattozzi and Merlo(2008)といった理論的な研究が挙げられる。前者は状況次第では報酬の上昇が能力の高い市民の立候補の確率を下げること、後者は民間企業を考慮した場合に報酬の上昇が政治家の平均的な質を下げる可能性があることをそれぞれ示している。したがって報酬の上昇が政治的なパフォーマンスの低下につながる可能性も十分にある中で、日本の地方議会に着目した時に報酬額の変動が議会活動にどちらの方向の影響を与えるかについて検討した研究は筆者の知りうる限り存在しない。さらに、立候補者が定員に満たない場合に無投票当選となり選挙そのものが発生しない日本においては、立候補者数が自治の質のみならず選挙による民主主義の維持という面でそれ自体重要な変数と考えられるため、パフォーマンス（議会活動の状況）と合わせて報酬による影響を明らかにする必要があると考えられるが、海外の先行研究の中で立候補者数を直接の被説明変数として扱っているものは多くない。\par
　日本の市町村レベルにおけるこうした影響の推定上の問題としては、先述したGagliarducci and Nannicini(2013)などの状況とは異なり、説明変数である議員報酬が外生的に決定されるわけではなく、各市町村の社会経済的な状況に加え、過去の選挙における立候補者数や過去の議員活動の記録などによって決められている可能性があるという側面がある。このような説明変数がフィードバック的に決定される可能性がある状況下においては、固定効果モデルを分析に用い各市町村の時間を通じて一定な観測不可能な要因をコントロールしたとしても、分析対象の影響に関して、推定量は一致性を持たず、厳密な因果効果の推定にならないとされている。そこで本研究ではこうした状況においても推定量が一致性を持つことが知られるダイナミックパネルモデルを分析に用い、因果効果に迫ることを試みている。\par
　また、この研究においては、特に議員報酬額の議会活動に与える影響に関して、推定後にその経路についても議論を行いたいと考えている。Gagliarducci and Nannicini(2013), Ferraz and Finan(2009)などの先行研究では、この影響の経路について主に当選議員の能力・質が変化による経路と議員のインセンティブの変化による経路の2種類が存在するとされている。今後、各議員の年齢によって後者の経路のみが変化するという仮定の下で、議会の平均年齢によってサンプルを分けサンプル間での影響の推定値の違いを見ることで、全体に占める後者の経路の割合についての示唆を与えたいと考えている。\par
　データについては、議会報酬額及び議会活動の指標に関して、全国町村議会議長会による町村議会実態調査及び全国市議会議長会による市議会の活動に関する実態調査、市議会議員定数・報酬に関する調査、市議会議員の属性に関する調査の結果が一部公表されており、その部分を用いている。また、立候補者数など選挙についての変数は、各市町村の選挙管理委員会発表情報の集計事業を行っている民間企業、イチニ株式会社が提供する選挙情報プラットフォーム「選挙ドットコム」に掲載されているデータを用いている。さらに各市町村の財政状況や人口構成等に関する変数は、総務省による地方財政状況調査の結果および総務省統計局による「統計でみる都道府県・市区町村のすがた（社会・人口統計体系）」のデータを用いている。\par
 第 \@ref(theory-literatures) 節は先行研究のサーベイである.


# 理論的背景と先行研究 {#theory-literatures}


## 理論的背景

 議員報酬が選挙や議会のパフォーマンスにどのような影響を与えるかに関する理論的な議論は、伝統的に、政治学(political science)・政治経済学(political economy)・公共経済学(public economics)などの分野で、主としてゲーム理論の枠組みを用いた「フォーマル・モデル」によって進んできた。理由としては、政治家の労働市場は、一般的な労働市場と異なり、選挙を介したシステムであり、候補者間の政治定主張の相互作用や、他の候補者の主張や能力を考慮した候補者の戦略が、アウトカムに大きな影響を及ぼすためである。過去の文献は、議員報酬の増額は、均衡における、選挙への立候補者人数、候補者・当選者の「能力」、再選のインセンティブ、およびそれらの変動の結果としての任期中のパフォーマンスに影響を与えるとしている。\par
 
 
### 効率賃金理論 (efficiency wage theory)

　効率賃金理論(efficiency wage theory)は、労働者の実質賃金が高く設定されればされるほど労働生産性が高まるという、労働経済学(labor economics)の分野における古典的な理論の一つである。この理論は、報酬が政治家に与える影響に関して、フォーマル・モデルに依らずに予測を与えているほとんど唯一の理論であるといえる。\par
　高い賃金が労働生産性を高める経路としては、(1) 解雇されるコストが上昇し、義務を怠らなくなること(Shapiro and Stiglitz, 1984)、(2) 職への応募者の質が高まること(Weiss,1980)、(3) モチベーションと規律が高まること(Akerlof,1982)　の3つが挙げられる。Gagliarducci and Nannicini(2013)によれば、これらの経路は、政治家の労働市場の文脈では、再選のインセンティブが高まること、より優秀な人材が集まること、政治家のモラルが向上することに対応するとし、これらを通じて、パフォーマンスが高まるとしている。\par
　もちろんこの理論には、政治家の労働市場に固有の、選挙運動や金銭に依存しないインセンティブ、有権者の選好などの影響を考慮していないという側面が存在する。しかし、次項以降に紹介する選挙などを考慮した他の理論・モデルにおいても、この理論の予測と整合的な予測を与えているケースは多い(Gagliarducci and Nannicini,2013)。

　
### 市民候補者モデル (citizen-candidate model)

　市民候補者モデル(citizen-candidate model)は、Osborbe and Slivinski(1996)及びBesley and Coate(1997)がゲーム理論の枠組みを用いて考案した、与えられた条件の下でのプレイヤー(市民)の選挙への立候補の挙動の予測を行うモデルである。このモデルの中では、各プレイヤーの利得は、自身の理想の政策と実際の政策の乖離、出馬のコスト、政策とは無関係の議席・政権を得ることのベネフィットの3つの合計として記述され、報酬は、3つ目の利得の一部として解釈される。\par
　Osborbe and Slivinski(1996)による最も古典的なモデルに依れば、個人が自身の理想の政策と最も近い政策を掲げる候補者に投票するというルールの下で、出馬のコストに比して政策とは無関係の議席を得ることのベネフィットが大きくなるほど立候補人数は増えることが示唆されていることから、報酬は立候補人数に正の影響を与えると考えられる。\par
　こうした市民候補者モデルの中には、立候補者や政治家の「能力」「質」を考慮したモデルも存在する。例えば、Caselli and Morelli(2004)は、民間市場での能力と政治的な能力が相関しているという設定を考え、そうした状況下で、議席・政権を得ることの金銭面でのベネフィットが減るほど、立候補者に占める能力の高い人の割合が減るという理論的予測を提供している。一方で、Messner and Polborn(2004) や、動的平衡モデル(dynamic equilibrium model)を用いたMatozzi and Merlo (2008) などは報酬が増加した場合、候補者の「質」が低下する可能性があることを指摘している。前者は報酬の上昇がより多くの人の政治への参加を促すため設定によっては能力の高い個人が「フリーライド」を行い立候補しないという選択を行う確率が高いこと、後者はリタイアまで政治家であり続けるキャリア政治家(career politicians)と民間企業でも働く政治家キャリア(political careers)という政治家の区別を行ったうえで場合によっては報酬の増額で政治家キャリアの割合が減り政治家の質が低下する可能性があることを指摘している。このほか、Poutvaara and Takalo(2007)が考案した政党による予備選挙・候補者選びのプロセスを考慮したモデルにおいても、選挙運動の費用が高いとき、報酬の増額は必ずしも候補者の平均的な質を高めないことを指摘している。\par
　結果として、市民候補者モデルに基づいた理論的な議論においては、報酬の増額は選挙における候補者の数を増やすことが示されている一方、候補者・政治家の能力にどのような影響を与えるかは意見が分かれている。\par


### 政治的エージェンシー理論モデル (political agency model)

　Gailmard(2014)などに基づくと、主体(プリンシパル)がどのようにして委任先(エージェント)の日和見主義を防ぎ自身が最も好む意思決定を行わせるインセンティブを与えるかに関する理論であるプリンシパル・エージェンシー理論(principal-agent theory)はしばしば政治の文脈でも用いられる。本稿では、こうした政治的エージェンシー理論モデル(political agency model)には、プリンシパルを市民、エージェントを政治家とした electoral agency と呼ばれるモデルが存在する。\footnote{他に政治家をプリンシパル、官僚をエージェントとした bureaucratic agency のモデルも存在する。}。つまり、間接民主制のシステムを通じて、市民が政治家に国家・自治体の運営権を委託しているという考え方に基づいた議論がなされているのである(Ferejohn,1986など)。本稿ではこの議論に焦点を当てる。これらの考え方に基づいたフォーマルモデルは、主に政治家の報酬が増えた場合に、彼らのパフォーマンスにどのような影響を与えるかに関して示唆を与えている。
　政治家の報酬の影響に関する研究のうち、最も興味深い示唆を与えているのは、Besley(2004)である。この研究においては、政治家は「良い政治家(congruent)」と「悪い政治家(dissonant)」の2種類が存在することが仮定されており、前者は常に有権者の目的に沿って行動する一方で、後者は有権者の望む行動と異なる行動をとることで自分自身の利益を得ようとするとされている。報酬が増加した場合、再選のインセンティブが高まり、後者のタイプであっても任期中に有権者の望む行動をとることが増えることが示唆されている(規律効果)。一方で、後者のタイプのこうした行動は、有権者による現職者のタイプの判別を難しくさせ、選挙において悪いタイプを再選させてしまうことにもつながるとされている(選択効果)。
　他にも、


## 実証研究



# 仮説 {#hypothesis}


## 先行研究の整理

　前章で紹介した理論モデルは、政治家の報酬をモデルのパラメータとして外生的に与え、その帰結として、選挙への立候補者人数、候補者・当選者の能力、再選のインセンティブ、ひいては政治的なパフォーマンスにどのような影響を与えるかを考察している。これらの理論的予測を整理し、以下のような仮説を立てることができる。\par
\vskip\baselineskip

- **仮説1: 議員報酬が高まるほど、選挙における1議席当たりの立候補者人数は増える。**
\vskip\baselineskip

- **仮説2a: 議員報酬が高まるほど、選挙における立候補者の能力が高まる。**
\vskip\baselineskip

- **仮説2b: 議員報酬が高まるほど、選挙における立候補者の能力は低くなる。**
\vskip\baselineskip

- **仮説3: 議員報酬が高まるほど、議会におけるパフォーマンスが高まる。**
\vskip\baselineskip

　ここで、能力はGagliarducci and Nannicini(2013)などの先行研究に倣い、立候補前の職業により測定できると仮定する。同様に議会におけるパフォーマンスに関しても、Ferraz and Finan(2009)などを考慮し、議員提案条例の提出数・可決数により代理されると考える。\par
　上記の通り、仮説2aと仮説2bは互いに対立する仮説となっているが、これは、先行研究の相反する理論的予測を反映したものである。さらに、仮説3に関しては議員報酬の上昇により再選のインセンティブや政治家の規律は高まり、前章で紹介した過去の実証研究を総合的に勘案すると議員報酬がパフォーマンスに与える影響の経路としては能力の変化によるものよりも再選のインセンティブの変化・規律の変化によるものの方が大きいと考えられるために、仮に仮説2bが支持されたとしても報酬はパフォーマンスに正の影響を与えると考えられる。
　

## 内生的な議員報酬の操作の影響

　さて、ここまでは主要な理論に基づく先行研究に倣い、あくまで国など上位の主体により、議員報酬は外生的に決定されるという仮定の下で、その影響を考えてきた。本稿においてはこの仮定を緩め、議員・議会による自発的な議員報酬の操作を考慮に入れる\footnote{当然、このような内生的な議員報酬の操作を考慮する場合、実証分析において議員報酬の影響をバイアスなく推定することは困難を極める。本章ではこの問題については深く立ち入らず、内生性が示唆する理論的予測のみに焦点を当てる。}。これは、筆者の知りうる限り、これまでの先行研究がほとんど扱ってこなかった状況であるが、本稿で扱う日本の地方議会などはこうした状況に当てはまり、この場合に議員報酬の増額がどのような影響を与えるかの考察を与えることは、極めて重要である。\par
　例えば、日本においては、議員報酬を含む地方議員・政治家の金銭的なリターンは、地方自治法第203条により条例により定められることが規定されている。すなわち、議員報酬の操作は、議員自身の行動の結果である条例改正に依って行われるのである\footnote{多くの自治体では報酬額に対して提言を行う審議会が存在する一方で、日本における地方議会議員報酬の変遷について述べている数少ない文献の1つである堀内(2016)はそうした審議会が実質的に議会の支配下に置かれることも多いとしている。}。本稿において着目したい点は、こうした議員による条例改正は、議員の業績の1つであり、議員が発する「メッセージ」になってしまうという点である。\par
　こうした業績は、選挙において、有権者が投票先を決定する際の有用な情報になりうる。実際、投票行動のモデルの一つである回顧投票・業績評価投票(retrospective voting)においては、有権者は過去の議会・政府の業績に基づいて投票行動を決定することが指摘されており(Key,1966)、さらに条例改正という行動は、地方議会・議員の業績として考えるのは妥当であると思われる。\par
　業績評価投票においては、有権者は業績が良い場合に政権への支持票を通して政権を賞し、業績が悪い場合には野党への支持票を通して政権を罰するとされる(Key,1966)。ここで問題となるのは、仮に議会が「議員報酬の増額」という条例改正を行った場合に有権者はどういった業績評価を下すかというである。これは、有権者が「議員報酬の増額」を正当なものと考えるかどうかに依存すると考えられる。\par
　先述のように、政治家の報酬に政治的なパフォーマンスに与える影響が正であることについては、学術的には、理論的・実証的に合意が得られつつある。従って、少なくとも長期的な目線に立った場合、増額は良い影響を与えるケースも多いと考えられる。一方で有権者がこうした議員報酬の正の影響に関して、知ることができるかという点には、大きな問題がある。もし、そのような正の影響を知らない場合には、有権者は増額に関して、ぞの理由如何によっては、政治家による自身の利益追求行為(「レント・シーキング」)とみなすかもしれない。さらには、税金における自らの取り分が不当に減らされたと考えるために、良い印象を抱かない可能性もある。\par
　
　ここにおいて、大きな問題となるのは、有権者が「議員報酬の変動」という現象は観察できる一方で、その変動の決定に至ったプロセスやその理由を完全には把握できない可能性があるということである。エージェンシー理論においては、プリンシパルとエージェンシーの間には情報の非対称性が存在し、プリンシパルはエージェントが持つ情報やエージェントによる意思決定を全て把握することは難しいとされるが、こうした両者の関係性は政治的エージェンシー理論においても成り立つのである(Canes-Wrone, Herron, and Shotts,2001なども指摘している)。こうした情報の非対称性の下では、仮に正当な理由があり議員報酬の増額が行われたとしても、有権者はその正当な理由を把握できず、税金における政治家の取り分が不当に増やされ、自身の取り分が不当に減らされたと考えた末に不満を覚え、選挙においてそうした決定を行った議員を「罰」するかもしれない。また、逆に減額が行われた場合、それが適切な理由な下で行われていない場合であっても、税金における政治家の取り分の一部が自身に移転されたと感じ満足感を覚え、そのような「身を切る」改革を行った議員を「賞」するかもしれない。従って、業績評価投票及び情報の非対称性の仮定の下で以下の仮説が導かれる。
\vskip\baselineskip

- **仮説4: 議員報酬の増額が行われた場合、次の選挙における現職者の得票率は増額しない場合に比べ下がる。**
\vskip\baselineskip

- **仮説5: 議員報酬の減額が行われた場合、次の選挙における現職者の得票率は減額しない場合に比べ上がる。**
\vskip\baselineskip

- **仮説6: 議員報酬の増額が行われた場合、次の選挙における多数会派の得票率は増額しない場合に比べ下がる。**
\vskip\baselineskip

- **仮説7: 議員報酬の減額が行われた場合、次の選挙における多数会派の得票率は減額しない場合に比べ上がる。**
\vskip\baselineskip
　
　以上の仮説は、地方議会において、有権者が業績に基づいて賞罰を与える対象が現職者や議会の多数派であるという可能性に基づいている。なお、ここでの「得票率」は、仮説１・２で提示された立候補人数の増加や候補者の能力の高まりをコントロールした上でのものであることに注意されたい。\par
　上記と同様の論理で、「増額」は有権者に地方自治に対する不信を与えるかもしれない。また「減額」は地方自治に対する信頼を高めるかもしれない。有権者の信頼・不信が選挙における参加・棄権の選択に影響を与えることが複数の文献(Grönlund and Setälä,2007; Cox,2003 ほか)で示唆されているため、追加的に以下の仮説を立てる。
\vskip\baselineskip

- **仮説8: 議員報酬の増額が行われた場合、次の選挙における投票率は増額しない場合に比べ下がる。**
\vskip\baselineskip

- **仮説9: 議員報酬の減額が行われた場合、次の選挙における投票率は減額しない場合に比べ上がる。**
\vskip\baselineskip
　
　さて、ここまでの議論における最大の仮定は、有権者と議員の間の情報の非対称性に基づいた「有権者は議員報酬の改定は観察できるがその理由までは観察できない」というものである。この仮定が危うくなる可能性としては、2通りの状況を考えることができる。1つ目は情報の非対称性がより深刻で有権者が議員報酬の改定を認識できない状況であり、2つ目は情報の非対称性があまり深刻でなく、議員報酬の改定という現象に加え、その理由まで明確に観察できる状況である。前者のような場合には、そうでない状況に比べ仮に議員報酬に変化があっても、有権者の投票行動に変化は穏やかである可能性がある。また、後者のような場合には、政治家による説明責任(accountability)が果たされていると考え、増額した場合の懲罰や不信が和らぐ可能性がある(特に、増額が正当な理由で行われている場合にはこうした蓋然性は高いと考えられる)。\par
　ここでさらに問題になるのは、前段落での1つ目、2つ目の状況がどのような環境下で起きやすかという点である。本稿で注目したいのは、口頭でのコミュニケーション(「口コミ」)による情報の伝達とメディアによる報道の役割である。こうした情報伝達が円滑に行われる状況下では、前段落での2つ目の状況が起きやすい一方で、あまり活発ではない場合には、前段落での1つ目の状況が起きやすいと考える。また、人口が極端に少ない自治体では、口頭でのコミュニケーションによる情報の伝達はより活発になり、人口が極端に多い自治体では、メディアに注目を浴びやすいと考えられる為、以下の仮説を立てる。\vskip\baselineskip
　
- **仮説10a: 人口が極端に少ない自治体あるいは多い自治体においては、そうでない自治体に比べ報酬の改定の影響にまつわる仮説4-9の関係性はより強く観察される。**
\vskip\baselineskip

- **仮説10b: 人口が極端に少ない自治体あるいは多い自治体においては、そうでない自治体に比べ報酬の減額の影響にまつわる仮説5,7,9の関係性はより弱く観察される。**
\vskip\baselineskip

　これらの仮説が互いに対立する仮説になっているのは、人口が極端に少ない自治体あるいは多い自治体においては、情報の非対称性があまり深刻にならずに、改定の理由まで観察できるようになる可能性(仮説10bに繋がる)のほか、改定それ自体が観察出来ないという状況が減る可能性(仮説10aに繋がる)があることで説明できる。


## 影響の「強さ」とシミュレーション

　前々節、前節において提示した仮説が本稿において検証を行う仮説の全てである。\par
　本稿においては、こうした仮説の検証だけでなく、それぞれの関係性における議員報酬の影響の強さも興味の対象の一つである。これは、ここまでの議論で示したように、議員報酬が内生性に決定される状況では、議員報酬の増加は地方自治に対してどちらかというと「良い」方向の影響(仮説1,2a,3)と「悪い」方向の影響(仮説2b,4-9)の両方を与える(ある種のトレードオフが存在する)可能性があり、トそれぞれの方向への影響の強さを定量的に明らかにすることは、今後日本において地方議会の議員報酬を改定すべきか・どの程度の値に設定すべきかという実務的な議論への大きな貢献に繋がると考えられる為である。したがって、実証分析の結果を解釈する際に、統計的有意性のみならず実質的な有意性にも大きな注意を払う。\par
　また、実務的な議論へより大きな示唆を与えるため、本稿では、仮に各自治体が議員報酬の改定を行った場合、選挙や議会にどのような変化が起きるかに関して、シミュレーションを行うことで明らかにする。シミュレーションでは、推定モデルに様々な仮想的な説明変数の値を与えた場合、被説明変数にどのような変化が起きるかを観察する予定である。
　
　
　

　

